version: "3.8"
services:
  db:
    image: postgres:latest
    build: ./database/
  app:
    image: 127.0.0.1:6001/counterdb
    build: ./app/
    ports:
      - "5000:5000"
    depends_on:
      - db